#!/bin/sh

# Colours
#
# Special
background='#25211D'
foreground='#EFF2F4'
cursor='#EFF2F4'

# Colors
color0='#25211D'
color1='#9C6D50'
color2='#D19C4D'
color3='#DC9E59'
color4='#7C7388'
color5='#D3BAA2'
color6='#D6DCE4'
color7='#EFF2F4'
color8='#7c7977'
color9='#9C6D50'
color10='#D19C4D'
color11='#DC9E59'
color12='#7C7388'
color13='#D3BAA2'
color14='#D6DCE4'
color15='#EFF2F4'

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config active_border_color $color4
bspc config normal_frame_opacity 0.0
bspc config focused_frame_opacity 0.1

bspc rule -a mpv state=floating

picom &
sxhkd &
polybar bsp &
~/.fehbg &
